name: Build and Deploy Documentation

on:
  # push:
  # branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    name: Build and Deploy
    environment:
      name: github-pages
      # Appending the DocC path so the runner shows the direct link
      url: ${{ steps.deployment.outputs.page_url }}documentation/leetcode/
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile Documentation
        run: |
          # 1. Download the web renderer templates
          git clone https://github.com/apple/swift-docc-render-artifact.git .docc-render
          export DOCC_HTML_DIR="$(pwd)/.docc-render/dist"

          # 2. Run the build as before
          mkdir -p docs
          OUTPUT_PATH=$(pwd)/docs
          cd swift
          swift package --allow-writing-to-directory "$OUTPUT_PATH" \
            generate-documentation --target LeetCode \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path ${{ github.event.repository.name }} \
            --output-path "$OUTPUT_PATH"

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs"

      - name: Deploy Artifact
        id: deployment
        uses: actions/deploy-pages@v4
