name: Build Docs

on:
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    working-directory: swift

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore file mtimes
        uses: chetan/git-restore-mtime-action@v2

      - name: Cache SPM
        uses: actions/cache@v5
        with:
          path: swift/.build
          key: spm-${{ runner.os }}-${{ hashFiles('swift/Package.resolved') }}-${{ github.sha }}
          restore-keys: |
            spm-${{ runner.os }}-${{ hashFiles('swift/Package.resolved') }}-

      - name: Setup web renderer
        run: |
          git clone https://github.com/apple/swift-docc-render-artifact.git .render
          echo "DOCC_HTML_DIR=$(pwd)/.render/dist" >> $GITHUB_ENV
          echo "Renderer cloned to $(pwd)/.render/dist"

      - name: Update documentation catalog
        run: swift generate-docc-topics.swift

      - name: Generate DocC
        run: |
          swift package \
            --allow-writing-to-package-directory \
            generate-documentation \
            --target LeetCode \
            --output-path ./docs \
            --transform-for-static-hosting \
            --hosting-base-path "${{ github.event.repository.name }}"

          [ -f "docs/index.html" ] || { echo "::error::Index file missing"; exit 1; }
          echo "Docs generated at ./docs (base path: ${{ github.event.repository.name }})"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: swift/docs
