name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    name: Test
    uses: ./.github/workflows/build-and-test.yml

  coverage:
    name: Coverage
    needs: test
    uses: ./.github/workflows/report-coverage.yml
    with:
      report-file: ${{ needs.test.outputs.report-file }}
      coverage-artifact: ${{ needs.test.outputs.coverage-artifact }}

  deploy-docs:
    name: Deploy Docs
    needs: test
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/publish-docs.yml
    secrets: inherit
