name: Publish Docs
on: workflow_call

defaults:
  run:
    working-directory: swift

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup web renderer
        run: |
          git clone https://github.com/apple/swift-docc-render-artifact.git .render
          # Export to environment for subsequent DocC command
          echo "DOCC_HTML_DIR=$(pwd)/.render/dist" >> $GITHUB_ENV

      - name: Generate DocC
        run: |
          swift package \
            --allow-writing-to-package-directory \
            generate-documentation \
            --target LeetCode \
            --output-path ./docs \
            --transform-for-static-hosting \
            --hosting-base-path "${{ github.event.repository.name }}"

          [ -f "docs/index.html" ] || { echo "::error::Index file missing"; exit 1; }

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: swift/docs

  publish:
    name: Publish
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}documentation/leetcode/
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        id: deployment
        uses: actions/deploy-pages@v4
